[package]
name = "iroha_python"
version = "0.1.0"
authors = ["Iroha 2 team <https://github.com/orgs/soramitsu/teams/iroha2>"]
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["generate"]

[lib]
name = "iroha2"
crate-type = ["cdylib"]

[dependencies]
iroha_client = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-lts" }
iroha_config = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-lts" }
iroha_crypto = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-lts" }
iroha_data_model = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-lts" }
iroha_version = { git = "https://github.com/hyperledger/iroha", branch = "iroha2-lts" }

color-eyre = "0.6"
parity-scale-codec = "3.1"
pyo3 = { version = "0.16.6", features = ["extension-module", "multiple-pymethods"] }
pythonize = "0.16.0"
serde = "1"
serde_json = "1"
