[package]
name = "iroha_config_derive"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
iroha_macro_utils = { workspace = true }

syn = { workspace = true, features = ["derive", "parsing", "proc-macro", "clone-impls", "printing"] }
# This is the maximally compressed set of features. Yes we also need "printing".
quote = { workspace = true }
proc-macro2 = { workspace = true }
proc-macro-error = { workspace = true }

