[package]
name = "iroha_schema"

edition.workspace = true
version.workspace = true
authors.workspace = true

license.workspace = true

[lints]
workspace = true

[dependencies]
iroha_schema_derive = { workspace = true }

serde = { workspace = true, features = ["derive", "alloc"] }
fixnum = { workspace = true, features = ["i64"] }

[dev-dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "full"] }
impls = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
